![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
np.__version__

'1.26.0'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [8]:
my_array = np.array(range(0, 10))
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [10]:
triple_array = np.array([[True, True, True], [True, True, True], [True, True, True]])

print(triple_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [24]:
for i in my_array:
    if i % 2 == 1:
        print(i)


1
3
5
7
9


[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [29]:
my_array.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [37]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a, b)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


In [39]:
np.concatenate((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [40]:
np.concatenate((a, b), axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [52]:
aa = np.array([1,2,3,2,3,4,3,4,5,6])
bb = np.array([7,2,10,2,7,4,9,4,9,8])

In [53]:
np.intersect1d(aa, bb)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [54]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [65]:
my_array_2 = np.arange(10)
print(my_array_2)

multip_array_2 = my_array_2 * 10
print(multip_array_2)

print(my_array_2[0])
print(my_array_2[-1])
print(my_array_2[1:8])

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [69]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [70]:
x = np.arange(1, 50, 3)
print(x)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [71]:
y = np.arange(4, 1, -0.25)
print(y)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [78]:
from skimage import imread


import matplotlib as mtp

imagen = imread('./img/numpy.png')

ImportError: cannot import name 'imread' from 'skimage' (c:\Users\taylo\AppData\Local\Programs\Python\Python311\Lib\site-packages\skimage\__init__.py)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

[[1]
 [2]
 [3]
 [4]]


array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

[[[19 13 14]
  [10 19 11]
  [19 11 14]
  [11 18 12]
  [14 12 15]]

 [[19 16 12]
  [15 15 11]
  [14 15 10]
  [12 12 13]
  [15 19 15]]

 [[12 17 18]
  [15 16 13]
  [15 11 12]
  [13 16 19]
  [19 18 10]]

 [[13 17 14]
  [18 11 12]
  [14 11 15]
  [15 16 11]
  [19 10 15]]]


3
(4, 5, 3)
60


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

[[[18 19 11 12 12 19]
  [15 14 11 16 13 11]]

 [[14 19 18 14 16 12]
  [19 16 12 15 12 17]]

 [[15 11 11 17 15 14]
  [12 18 18 17 18 10]]

 [[18 19 12 10 17 16]
  [10 17 15 11 18 15]]

 [[19 16 13 17 17 15]
  [13 18 17 13 15 19]]]
