![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(0, 10)
print(my_array)

print(my_array[: : -2])



[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [2]:
print(my_array[7: 9])

revers = my_array[::-1]

print(revers[1:3])


[7 8]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [3]:
my_array_nonine = my_array[0:9]
print(my_array_nonine)
my_array_nonine.reshape(3, 3)

print(my_array_nonine[2:3])
print(my_array_nonine[1:2])
print(my_array_nonine[0:1])

[0 1 2 3 4 5 6 7 8]
[2]
[1]
[0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [4]:
matriz = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
flipped = np.flip(matriz)

print(flipped)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [6]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
print(matriz[0:2:, 0:2:])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [8]:
print(matriz[0:5:2, 0:5:2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [9]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
print(matriz[0:3:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [11]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x == 'Loro')
x_loro = np.array(x == 'Loro')
print(x[x_loro])

[ True False False  True False]
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [12]:
sec = np.arange(20)
print(sec)

print(sec.reshape(2, 5, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [13]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [14]:
arr = np.array(np.flip(matriz))
arr

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [15]:
zero = np.zeros(10)
print(zero)

print(zero.dtype)

zero[3] = 1

print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [16]:
vect = np.arange(10, 50)
print(vect)

print(vect[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [17]:
vecto = np.array([1,2,0,0,4,0])

print(np.nonzero(vecto))
print(vecto.dtype)


(array([0, 1, 4], dtype=int64),)
int32


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [18]:
mixto = np.random.randint(100, size=(10,10))
print(mixto)

print(np.max(mixto))
print(np.min(mixto))

[[37 42 77 42 64 26 72 70 37 28]
 [81 76  4 50 93 49 41 72 30  6]
 [10  2  1 60 35 39 34 79  0 56]
 [49 73 20 72 26 78 75  4 20 20]
 [54 12 82 81 17 35 51 98 86 88]
 [24 22 48 78 63 80 78 91 71 71]
 [96 47 30 42 30 84 43  3 78 55]
 [41 90 72 70 35 48  7 16 63 89]
 [52  2 35 63 58 77 12 20 40 72]
 [37 26 74 74 38 60 45 22 15  6]]
98
0


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [19]:
ran= np.random.random(30)
print(ran)

print(np.mean(ran))

[0.99564874 0.34072207 0.96633819 0.802393   0.27969971 0.99166713
 0.39600079 0.83150982 0.60523097 0.00251764 0.07229562 0.86618923
 0.22118359 0.31440598 0.56829605 0.50346698 0.46866488 0.38438067
 0.16425906 0.70497163 0.97704262 0.90442105 0.15567671 0.42098511
 0.69124272 0.63697327 0.69623288 0.67106967 0.83236352 0.92489699]
0.5796915430433579


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [20]:
cuadrado = np.ones((5,5))
print(cuadrado)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
cuadrado[1,1] = 0
cuadrado[1,2] = 0
cuadrado[1,3] = 0
cuadrado[2,1] = 0
cuadrado[2,2] = 0
cuadrado[2,3] = 0
cuadrado[3,1] = 0
cuadrado[3,2] = 0
cuadrado[3,3] = 0
print(cuadrado)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [159]:
mix = np.ones((8, 8))

mix[0::2, 0::2] = 0
mix[1::2, 1::2] = 0

print(mix)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [172]:
ej_18 = np.array([[0, 1], [1, 0]])
print(ej_18)

resul = np.tile(ej_18, (4, 4))
print(resul)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [177]:
ej_19 = np.random.randint(20, size=(5,5))
print(ej_19)

[[ 4  7  9  7 13]
 [10 13 16  0  3]
 [18 19  3  1 14]
 [11  7  7 13  7]
 [12  0  2 15  3]]


In [188]:
media = ej_19 - ej_19.mean()

newmedia = media / media.std()
print(newmedia)


[[-0.81838794 -0.27997482  0.07896726 -0.27997482  0.79685141]
 [ 0.2584383   0.79685141  1.33526453 -1.53627209 -0.99785897]
 [ 1.6942066   1.87367764 -0.99785897 -1.35680105  0.97632245]
 [ 0.43790933 -0.27997482 -0.27997482  0.79685141 -0.27997482]
 [ 0.61738037 -1.53627209 -1.17733001  1.15579349 -0.99785897]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [252]:
ej_20 = np.arange(0, 11)
print(ej_20)

x = -1
y = ej_20 > 8

ej_20_1 = np.where((ej_20 > 3) & (ej_20 < 8), x, ej_20)
print(ej_20_1)

ej_20_2 = np.where((ej_20 > 3) & (ej_20 < 8), -ej_20, ej_20)
print(ej_20_2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.